spring.application.name=iot-backend
server.port=8088

# Cấu hình MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/iot_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ========== MQTT Configuration ==========
mqtt.broker.url=tcp://broker.emqx.io:1883
# Đổi client.id mang tính định danh riêng để không bị đụng hàng
mqtt.client.id=spring-iot-backend-${random.uuid}
mqtt.username=
mqtt.password=

# Thêm tiền tố riêng biệt cho topic (ví dụ: hip_iot/...)
mqtt.topic.sensor-data=hip_iot/sensors/data
mqtt.topic.device-control=hip_iot/device/{id}/control
mqtt.topic.device-status=hip_iot/device/{id}/status

# ========== WebSocket Configuration ==========
server.servlet.context-path=/